### ISSUE TITLE
exp() overflow

### ISSUE THREAD

**Issue by jmuth** [jmuth/PCML_project1#2]
Fix the overflow and the slow execution time by estimating exp() and sigma() function in the .py algorithms, following the exp_overflow notebook

**Comment by junzebao** [comment]
Solved: standardize data and scale it to [-1, 1] could eliminate overflow. Codes to deal with overflow are also added though. Use the following equations to estimate:
1. log(1 + exp(s)) = s, if exp(s) overflows, meaning s > 710 approximately
2. sigmoid, when t is a number, exp(t) / (1+exp(t)) ~ 1.
